### PR TITLE
[WIP] Build FLTK for ZynAddSubFX support

### PR DESCRIPTION
**Pull request by PhysSong**
Per https://github.com/LMMS/lmms/issues/4109#issuecomment-489376981

### CODE REVIEW

**Comment by hfiguiere** [comment]
You still have this marked as [WIP]. Anything you'd like to add?

It builds properly and the ZynAddSubFX is there.
However there UI never show when I click on "Show UI"

**Comment by PhysSong** [comment]
@hfiguiere Did you get some terminal output like this?
```
Could not connect to local server.
Error while writing.
```

**Comment by hfiguiere** [comment]
yes I'm getting these.

**Comment by PhysSong** [comment]
As you can see in https://github.com/LMMS/lmms/blob/ec64de072352c17a025e073114aaaea6ba773822/src/core/RemotePlugin.cpp#L102-L104, LMMS uses local sockets on the temporary directory. I suspect there were some permission issues with the sockets.
```cpp
	m_socketFile = QDir::tempPath() + QDir::separator() +
						QUuid::createUuid().toString();
	const char * path = m_socketFile.toUtf8().constData();
```

**Comment by hfiguiere** [comment]
still doesn't work here.

**Comment by hfiguiere** [comment]
It fails because

```
bind(33, {sa_family=AF_UNIX, sun_path="/var/tmp/{9879ab2c-c2c8-4a1b-aa28-fa3b5f6276a0}"}, 110) = -1 EROFS (Read-only file system)
```

**Comment by hfiguiere** [comment]
Solution is to add `"--filesystem=/var/tmp"` (since this is what `TMPDIR` is set to) instead of `"--filesystem=host"`.

**Comment by PhysSong** [comment]
> Solution is to add `"--filesystem=/var/tmp"` (since this is what `TMPDIR` is set to) instead of changing to `"--filesystem=host"`.

Okay. BTW, why did you set `TMPDIR` to `/var/tmp`? Are there any issues with default `/tmp`?

**Comment by hfiguiere** [comment]
Not setting `TMPDIR` make the additional filesystem permission unneeded.

That is also a reasonable solution.

**Comment by hfiguiere** [comment]
Cherry-picked the fltk patch to master, added the proper change for plugin socket to work and rolled all out for the 1.2.0 release that should be building right now. 

Thanks you so much.

**Pull request closed without merging**
